apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
data: 
  proxysql.cnf: |
{{ tpl (.Files.Get "files/proxysql.cnf") . | indent 4 }}
  probe-proxysql.bash: |
{{ tpl (.Files.Get "files/probe-proxysql.bash") . | indent 4 }}
  maintain-cluster.rb: |
{{ tpl (.Files.Get "files/maintain-cluster.rb") . | indent 4 }}
  my.cnf: |
{{ tpl (.Files.Get "files/my.cnf") . | indent 4 }}
