apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxysql-leader-election
  namespace: proxysql
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
